### PR TITLE
Fix NFCTagReaderSession init unavailable in SDK 14.5

### LINKED ISSUE #448: Compiling error NFCTagReaderSession
NFCTagReaderSession new -> 'new' is unavailable

after update xcode debug tool

### PR DESCRIPTION
**Pull request by christiaan**
Since iPhoneOS14.5 the init function has been marked as unavailable.

Example error:

```
 /usr/local/opt/actions-runner/_work/mobile-app/mobile-app/platforms/ios/Leviy/Plugins/phonegap-nfc/NfcPlugin.m:128:53: error: 'new' is unavailable
            self.nfcSession = [[NFCTagReaderSession new]
                                                    ^
In module 'CoreNFC' imported from /usr/local/opt/actions-runner/_work/mobile-app/mobile-app/platforms/ios/Leviy/Plugins/phonegap-nfc/NfcPlugin.h:11:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/System/Library/Frameworks/CoreNFC.framework/Headers/NFCTagReaderSession.h:100:1: note: 'init' has been explicitly marked unavailable here
- (instancetype)init NS_UNAVAILABLE;
^
```

Fixes https://github.com/chariotsolutions/phonegap-nfc/issues/448

### CODE REVIEW

**Comment by christiaan** [comment]
I have not been able to verify this actually works. I could compile it and run in the simulator.

**Review by bartvanvelden — APPROVED** [review]

**Comment by pmanup** [comment]
> I have not been able to verify this actually works. I could compile it and run in the simulator.

yes, work

**Comment by gnarco** [comment]
I confirm, it works.

Could it be merged ?

**Comment by kamil-hammouche** [comment]
I'm encountering the same issue after updating Xcode to 12.5

```
            self.nfcSession = [[NFCTagReaderSession new]
                       initWithPollingOption:(NFCPollingISO14443 | NFCPollingISO15693)
                       delegate:self queue:dispatch_get_main_queue()];
```

The error is : 'new' is unavailable

How to fix this ?

**Comment by christiaan** [comment]
> I'm encountering the same issue after updating Xcode to 12.5
> 
> ```
>             self.nfcSession = [[NFCTagReaderSession new]
>                        initWithPollingOption:(NFCPollingISO14443 | NFCPollingISO15693)
>                        delegate:self queue:dispatch_get_main_queue()];
> ```
> 
> The error is : 'new' is unavailable
> 
> How to fix this ?

Wait for this PR to be merged. Or use the branch of this PR directly in your package.json.

```
-    "phonegap-nfc": "^1.2.0",
+    "phonegap-nfc": "github:christiaan/phonegap-nfc#master_fix-ios-new-disabled",
```

**Comment by gnarco** [comment]
Do you know when this PR will be merged and pushed to NPM ? Are we talking in days or weeks ?

**Review by gnarco — APPROVED** [review]

**Comment by gnarco** [comment]
@don what's the process for merging ? 

Thanks !

**Comment by marioshtika** [comment]
New update. I am not having this problem after updating to Xcode 13.

**Comment by christiaan** [comment]
> New update. I am not having this problem after updating to Xcode 13.

I can confirm that this is not needed anymore.
